### ISSUE TITLE
fatal error: gst/gstconfig.h: No such file or directory. Compilation terminated

### ISSUE THREAD

**Issue by Keerthana17** [TelepathyQt/telepathy-qt#4] opened 2016-06-23 18:37 UTC
Recently when I tried installing telepathy-qt for Debian without the apt sources packages, I encountered this error. I had to configure telepathy-qt from apt sources in the end. The exact ending of the error log was : 

Makefile:141: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/athena/telepathy-qt-stuff/telepathy-qt-0.9.6.1/obj-x86_64-linux-gnu'
dh_auto_build: make -j13 returned exit code 2
debian/rules:20: recipe for target 'override_dh_auto_build-arch' failed
make[1]: *** [override_dh_auto_build-arch] Error 2
make[1]: Leaving directory '/home/athena/telepathy-qt-stuff/telepathy-qt-0.9.6.1'
debian/rules:12: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

The entire log for building the code is really long and given [here](https://drive.google.com/open?id=0B8WLXO4eNniydkJadWpSdWZkUEk)

**Comment by Kaffeine** [comment] 2016-06-23 18:49
Hi.
It seems that you used outdated version of TelepathyQt with newer version of GStreamer. The issue is fixed by commit ec4a3d62b68a57254515f01fc5ea3325ffb1dbfb, so you can 1) apply the commit by yourself, or 2) Use TelepathyQt-0.9.7 or the master branch from fd.o or github. Actually, there is no difference between released sources and git repos yet.

**Closed** 2016-07-09 09:25 UTC
